### ISSUE TITLE
Maybe a memory leak has occurred

### ISSUE THREAD

**Issue by sunzigang** [shmuelzon/esp32-ble2mqtt#131]
When I run for 24 hours (obtained by MQTT uptime subscription), the memory has changed from around 80,000 to 61476 (obtained by MQTT freememory subscription)

In the .config file, I did nothing except configure MQTT and wifi related parameters.
Also, I didn’t make any changes to the app.

App version:      v0.15.0-11-gf0a3f55
ESP-IDF:          v4.3.1-29-ge493a4c30e

**Comment by sunzigang** [comment]
No, a memory leak did occur in the device_name_get interface. The malloc method is used to store "name", but it is not released anywhere.
![image](https://user-images.githubusercontent.com/35128999/139573181-5053e103-569e-48ee-848b-095b9f416903.png)

**Comment by sunzigang** [comment]
When I clear the list every 5 minutes, it does look like the picture above. It seems that I have too much Bluetooth, which can easily cause too much memory. In addition, what is the monitoring tool shown in the screenshot above? This is a very cool tool.

**Comment by shmuelzon** [comment]
> When I clear the list every 5 minutes, it does look like the picture above

Cleaning it up every hour was just a quick fix. Perhaps we can limit the number of devices we add to the list and when adding another that would go over that limit, clean it up then. That might work better in a noisy environment but adds some overhead each time a device is discovered.

> What is the monitoring tool shown in the screenshot above?

That would be [Home Assistant](https://www.home-assistant.io/), monitoring the FreeMemory topic.
```yaml
sensor:
  - platform: mqtt
    name: "BLE2MQTT-470C Free Memory"
    state_topic: "BLE2MQTT-470C/FreeMemory"
    unit_of_measurement: "KB"
    value_template: '{{ ((value | int) / 1024) | round(1) }}'
```
