### ISSUE TITLE
Setting values is not consitant

### ISSUE THREAD

**Issue by ithinkido** [shmuelzon/esp32-ble2mqtt#180]
**Describe the bug**
When using the ```/Set``` prefix , I am able to set values once. On most occasions , when  trying to send a second ```/Set``` the BLE side fails.  I do have a suspicion that this may be due to the data type formatting ( ??)  causing the device to think the message is incomplete, but I am unsure how I can verify this , nor am l I 100% sure if this needs to defined in the config. I have used the same format for sending data as is being reported from the device. 

**To Reproduce**
In essence , this is using a standard ```/Set``` command  plus the value. I am using the debug console on MQTT under Home Assitant to send the messages.  

For testing I am using the  same format as the revived packet ( 40,0)  to format the data I ```/Set``` , ie also (40,0).  Looking at the [source code](https://github.com/Ralim/IronOS/blob/662829ebd9530e83c460f7c5dfcd2d0ea8ff401e/source/Core/BSP/Pinecilv2/ble_handlers.h#L14)  from the device, I know the data is sent as a uint16 value .

**Configuration and logs**
My config file is as follows:
```yaml
{
    "network": {
        "wifi": {
            "ssid": "xxxxxxxxx",
            "password": "xxxxxxxxxxxx"
        }
    },
    "mqtt": {
        "server": {
            "host": "192.168.1.200",
            "port": 1883,
            "username": "xxxxxxxxx",
            "password": "xxxxxxxxx"
        },
        "publish": {
            "qos": 0,
            "retain": true
        }
    },
    "ble": {
        "whitelist": [
            "xxxxxxxxxxxx"
        ],
        "services": {
            "whitelist": [
                "f6d75f91-5a10-4eba-a233-47d3f26a907f"
            ],
            "definitions": {
                "f6d75f91-5a10-4eba-a233-47d3f26a907f": {
                    "name": "setting"
                }
            }
        },
        "characteristics": {
            "whitelist": [
                "00000001-0000-1000-8000-00805f9b34fb",
                "00000000-0000-1000-8000-00805f9b34fb"
            ],
            "definitions": {
                "00000000-0000-1000-8000-00805f9b34fb": {
                    "name": "save"
                },
                "00000001-0000-1000-8000-00805f9b34fb": {
                    "name": "temp"
                }
            }
        }
    }
}
```
here is a screen capture of MQTT debug to show the messages and data

![image](https://user-images.githubusercontent.com/52834821/219868438-12d7b379-7197-4155-9b82-0ddfa1617717.png)

Here is the serial log capture of a successful send and a failed send.

[failed_Set.txt](https://github.com/shmuelzon/esp32-ble2mqtt/files/10774436/failed_Set.txt)
[success_Set.txt](https://github.com/shmuelzon/esp32-ble2mqtt/files/10774437/success_Set.txt)

**Additional context**
I am happy to provide any further log or info if needed
